name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672/tcp
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 'jruby', 'truffleruby']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}

    - run: ruby -v
    - run: ruby -e "puts 'Hello World!'"

    - run: ruby test/amqp/client_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
    - run: ruby test/amqp/high_level_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
    - run: ruby test/amqp/properties_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}

    - run: bundle exec ruby test/amqp/client_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
    - run: bundle exec ruby test/amqp/high_level_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
    - run: bundle exec ruby test/amqp/properties_test.rb --verbose
      continue-on-error: true
      env:
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
