name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0']
    steps:
    - name: Install RabbitMQ
      run: sudo apt-get update && sudo apt-get install -y rabbitmq-server
    - name: Stop RabbitMQ
      run: sudo systemctl stop rabbitmq-server
    - name: Create RabbitMQ config
      run: |
        sudo tee /etc/rabbitmq/rabbitmq.conf <<'EOF'
        listeners.ssl.default  = 5671
        ssl_options.cacertfile = /etc/rabbitmq/rootCA.pem
        ssl_options.certfile   = /etc/rabbitmq/localhost.pem
        ssl_options.keyfile    = /etc/rabbitmq/localhost-key.pem
        EOF
    - name: Start RabbitMQ
      run: sudo systemctl start rabbitmq-server
    - name: Verify RabbitMQ started correctly
      run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done
    - name: Install mkcert
      run: brew install mkcert
    - name: Create local CA
      run: sudo CAROOT=/etc/rabbitmq ./mkcert/mkcert -install
    - name: Create certificate
      run: |
        sudo ./mkcert/mkcert -key-file /etc/rabbitmq/localhost-key.pem -cert-file /etc/rabbitmq/localhost.pem localhost
        sudo chmod +r /etc/rabbitmq/localhost-key.pem

    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run TLS tests
      run: bundle exec rake
      env:
        TESTOPTS: --name=/_tls$/
