name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672/tcp
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 'jruby', 'truffleruby']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}

    - run: ruby -v
    - run: ruby -e "puts 'Hello World!'"

    - name: Run the default task (JRuby)
      if: ${{ startsWith(matrix.ruby, 'jruby') }}
      run: jruby -G rake

    - name: Run the default task
      if: ${{ !startsWith(matrix.ruby, 'jruby') }}
      run: bundle exec rake
      env:
        TESTOPTS: --exclude=/_tls$/
        AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
